apiVersion: v1
data:
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cGdzM2NyM3RAcG9zdGdyZXM6NTQzMi9wb3N0Z3Jlcw==
  password: cGdzM2NyM3Q=
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-creds
